services:
  server-mgr:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        USER_ID: 1711
        GROUP_ID: 1711
    user: "1711:1711"
    stdin_open: true
    tty: true
    volumes:
      - bin:/usr/local/bin
      - jvm:/usr/lib/jvm
    depends_on:
      - java-mgr
    restart: "unless-stopped"

  java-mgr:
    build:
      context: .
      dockerfile: docker/JDockerfile
    volumes:
      - bin:/usr/local/bin
      - jvm:/usr/lib/jvm
    environment:
      PACKAGES: "openjdk-17-jre-headless openjdk-21-jre-headless"
    restart: "no"

volumes:
  bin:
  jvm:

